name: C++ CI

on:
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-26, macos-26-intel, windows-2022]
        # For macos-26, include /Applications/Xcode_26.4.1.app SDKROOT
        include:
          - os: macos-26
            SDKROOT: /Applications/Xcode_26.4.1.app
          - os: macos-26-intel
            SDKROOT: /Applications/Xcode_26.4.1.app


    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install deps
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "Using apt to install ninja"
          sudo apt update
          sudo apt -y -qq install ninja-build
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "Using brew to install ninja"
          brew install ninja
          echo "Setting MACOSX_DEPLOYMENT_TARGET to 26.0"
          echo "MACOSX_DEPLOYMENT_TARGET=26.0" >> $GITHUB_ENV
          sudo xcode-select -switch "${{ matrix.SDKROOT }}"
          clang --version
          sdk_path=$(xcrun --sdk macosx --show-sdk-path)
          echo "sdk_path=$sdk_path" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "Window" ]; then
          choco install ninja
          # C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          MSVC_DIR=$(cmd.exe /c "vswhere -products * -requires Microsoft.Component.MSBuild -property installationPath -latest")
          echo "Latest is: $MSVC_DIR"
          echo "MSVC_DIR=$MSVC_DIR" >> $GITHUB_ENV
          # add folder containing vcvarsall.bat
          echo "$MSVC_DIR\VC\Auxiliary\Build" >> $GITHUB_PATH
        fi;

        NPROC=$(nproc 2>/dev/null || sysctl -n hw.logicalcpu)
        echo "There are $NPROC threads available"
        echo "NPROC=$NPROC" >> $GITHUB_ENV

    - name: Install conan
      shell: bash
      run: |
          python --version
          pip install conan
          conan --version
          echo "Enabling conan revisions and setting parallel_download"
          conan profile detect --force --name default
          conan profile path default
          conan profile show
          echo "core:non_interactive = True" >> $HOME/global.conf
          echo "core.download:parallel = {{os.cpu_count() - 2}}" >> $HOME/global.conf
          conan remote add nrel-v2 --index 0 --force https://conan.openstudio.net/artifactory/api/conan/conan-v2
          CONAN_PROFILE_DEFAULT=$HOME/.conan2/profiles/default
          sed -i.bak 's/cppstd=.*$/cppstd=20/g' $CONAN_PROFILE_DEFAULT
          sed -i.bak 's/build_type=.*$/build_type=${{ env.BUILD_TYPE }}/g' $CONAN_PROFILE_DEFAULT
          rm -Rf $CONAN_PROFILE_DEFAULT.bak || true
          conan profile show

    - name: Configure CMake And Build
      shell: bash
      run: |
        set -x
        conan install . --build=missing -c tools.cmake.cmaketoolchain:generator=Ninja -s compiler.cppstd=20 -s build_type=${{ env.BUILD_TYPE }} --output-folder=build
        cmake --preset conan-release
        cmake --build --preset conan-release

    - name: Run the executable
      shell: bash
      working-directory: build
      run: |
        ./main
